# Android Ruby Dependencies
source "https://rubygems.org"

# Ruby version
ruby ">= 3.3.0"

# Fastlane
gem "fastlane", "~> 2.225"

# Fastlane Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
