import 'package:firebase_auth/firebase_auth.dart';

String? currentUserId = FirebaseAuth.instance.currentUser?.uid;
String fcmServerToken = "AIzaSyC7FQUiD1_JUJbKmGl3vU-kIL-ju52uD7A";
String? chosenAge;
String? chosenCountry;
String? chosenGender;

List<String> religion = [
  "Christianity",
  "Islam",
  "Hinduism",
  "Buddhism",
  "Judaism",
  "Other",
  "None"
];

List<String> highSchool = [
  "High School",
  "Bachelor's",
  "Master's",
  "Doctorate",
  "Other"
];

final List<String> languages = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Polish',
  'Ukrainian',
  'Dutch',
  'Romanian',
  'Greek',
  'Chinese',
  'Tagalog',
  'Vietnamese',
  'Korean',
  'Arabic',
];

final List<String> nationalities = [
  'American',
  'British',
  'Canadian',
  'French',
  'German',
  'Italian',
  'Spanish',
  'Chinese',
  'Japanese',
  'Russian',
  'Brazilian',
  'Mexican',
  'Indian',
  'Australian',
  'Egyptian',
  'Nigerian',
  'South African',
  'Swedish',
  'Dutch',
  'Turkish',
];

final List<String> ethnicities = [
  'Han Chinese',
  'Arabs',
  'Bengalis',
  'Hispanics',
  'Punjabis',
  'Yoruba',
  'Javanese',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Ashkenazi Jews',
  'Hausa',
  'Gujarati',
  'Telugu',
  'Tamil',
  'Italians',
  'Turks',
  'Persians',
  'Pashtuns',
  'Fulani',
  'Igbo',
  'Oromo',
  'Azeri',
  'Malay',
  'Sundanese',
];

final List<String> livingSituations = [
  'Single-family home',
  'Apartment',
  'Shared house/flat',
  'Studio apartment',
  'Dormitory',
  'With parents',
  'Multigenerational household',
  'Retirement community',
  'Homeless shelter',
  'Temporary housing',
  'Mobile home',
  'Boat house',
  'Van life',
  'Co-living space',
  'Tiny house',
  'Assisted living facility',
  'Boarding house',
  'Commune',
  'Group home',
  'Homeless (street living)',
  'Hotel/motel long-term',
  'Squat',
  'Eco-village',
  'Military barracks',
  'Off-grid living',
];

final List<String> employmentStatuses = [
  'Full-time employed',
  'Part-time employed',
  'Self-employed',
  'Freelancer',
  'Contractor',
  'Unemployed (seeking work)',
  'Unemployed (not seeking work)',
  'Student',
  'Retired',
  'Homemaker',
  'Internship',
  'Apprenticeship',
  'Temporarily laid off',
  'On leave (e.g., maternity, medical)',
  'Seasonal worker',
  'Gig worker',
  'Remote worker',
  'Hybrid worker (part remote, part in-office)',
  'Business owner',
  'Volunteer',
  'Disabled (unable to work)',
  'Underemployed',
  'Multiple jobs',
  'Zero-hour contract',
  'Job-sharing',
];

final List<String> maritalStatuses = [
  'Single (never married)',
  'Married',
  'Divorced',
  'Widowed',
  'Separated',
  'Domestic partnership',
  'Civil union',
  'Engaged',
  'Cohabiting',
  'Common-law marriage',
  'Remarried',
  'Annulled',
  'Single (divorced)',
  'Single (widowed)',
  'Legally separated',
  'Married (living apart)',
  'Married (same-sex)',
  'Registered partnership',
  'In a relationship',
  'It\'s complicated',
];

final List<String> drinkingHabits = [
  'Non-drinker',
  'Social drinker',
  'Light drinker',
  'Moderate drinker',
  'Heavy drinker',
  'Recovering alcoholic',
  'Occasional drinker',
  'Drink on special occasions only',
  'Beer enthusiast',
  'Wine connoisseur',
  'Cocktail lover',
];

final List<String> smokingHabits = [
  'Non-smoker',
  'Light smoker',
  'Regular smoker',
  'Heavy smoker',
  'Trying to quit',
  'Former smoker',
  'Social smoker',
  'Vaper',
  'Cigar smoker',
  'Pipe smoker',
];

final List<String> bodyTypes = [
  'Slim',
  'Athletic',
  'Average',
  'Curvy',
  'Muscular',
  'A few extra pounds',
  'Heavyset',
  'Stocky',
  'Petite',
  'Tall',
  'Short',
];

final List<String> gender = [
  'Woman',
  'Man',
  'Transgender',
  'Non-binary',
  'Genderqueer',
  'Gender fluid',
  'Agender',
  'Bigender',
  'Two-Spirit',
  'Androgynous',
  'Demigender',
  'Genderqueer',
  'Gender non-conforming',
  'Questioning',
  'Prefer not to say',
  'Other (self-describe)',
];

// European Countries (Alphabetical Order)
List<String> countries = [
  'Belize',
  'Canada',
  'Costa Rica',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Mexico',
  'Nicaragua',
  'Panama',
  'United States',
  'Albania',
  'Andorra',
  'Austria',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
  'Bahrain',
  'Cyprus',
  'Egypt',
  'Iran',
  'Iraq',
  'Israel',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Oman',
  'Palestine',
  'Qatar',
  'Saudi Arabia',
  'Syria',
  'Turkey',
  'United Arab Emirates',
  'Yemen',
];
List<String> itJobs = [
  // IT and Technical Roles
  'Software Developer',
  'Data Scientist',
  'Cybersecurity Specialist',
  'Network Administrator',
  'System Administrator',
  'Cloud Architect',
  'DevOps Engineer',
  'Artificial Intelligence Engineer',
  'Mobile App Developer',
  'Web Developer',
  'Database Administrator',
  'UI/UX Designer',
  'QA Test Engineer',
  'Game Developer',
  'Blockchain Developer',
  'Technical Support Specialist',

  // IT Management Roles
  'IT Project Manager',
  'Chief Information Officer (CIO)',
  'Chief Technology Officer (CTO)',
  'IT Director',
  'Product Manager',
  'Scrum Master',
  'IT Business Analyst',

  // Human Resources Department
  'HR Manager',
  'Recruitment Specialist',
  'Training and Development Coordinator',
  'Compensation and Benefits Analyst',
  'Employee Relations Specialist',
  'HR Business Partner',
  'Talent Acquisition Manager',

  // Finance Department
  'Chief Financial Officer (CFO)',
  'Financial Analyst',
  'Accountant',
  'Financial Controller',
  'Payroll Specialist',
  'Tax Manager',
  'Internal Auditor',

  // Marketing Department
  'Chief Marketing Officer (CMO)',
  'Marketing Manager',
  'Digital Marketing Specialist',
  'Content Creator',
  'Brand Manager',
  'Social Media Coordinator',
  'Market Research Analyst',

  // Sales Department
  'Sales Director',
  'Account Manager',
  'Sales Representative',
  'Business Development Manager',
  'Customer Success Manager',

  // Operations Department
  'Chief Operating Officer (COO)',
  'Operations Manager',
  'Supply Chain Manager',
  'Logistics Coordinator',
  'Quality Assurance Manager',

  // Legal Department
  'General Counsel',
  'Legal Advisor',
  'Compliance Officer',
  'Intellectual Property Specialist',

  // Customer Service Department
  'Customer Service Manager',
  'Customer Support Representative',
  'Client Relations Specialist',

  // Research and Development
  'R&D Director',
  'Research Scientist',
  'Product Development Engineer',

  // Administration
  'Administrative Assistant',
  'Office Manager',
  'Facilities Manager',

  // Executive Leadership
  'Chief Executive Officer (CEO)',
  'President',
  'Board Member',
  'Executive Assistant'
];
