// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnJ_p6_fAEmMW58UQ6ygpAm08mEU4IUM',
    appId: '1:478614026227:android:f486f00d8891820d6d8486',
    messagingSenderId: '478614026227',
    projectId: 'tuncdating-ac461',
    storageBucket: 'tuncdating-ac461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8LjIvPsOUvpe6E1qc0zo6U0WI1ehSqc',
    appId: '1:478614026227:ios:e62c01189fdc95906d8486',
    messagingSenderId: '478614026227',
    projectId: 'tuncdating-ac461',
    storageBucket: 'tuncdating-ac461.appspot.com',
    androidClientId: '478614026227-u6c2ejklm2ogh8ts80ib056c77pdfr2b.apps.googleusercontent.com',
    iosClientId: '478614026227-9ldich368blehqdvelf3v3sovh2n02h8.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tuncdating',
  );

}