# iOS Ruby Dependencies
source "https://rubygems.org"

# Fastlane
gem "fastlane", "~> 2.225"

# Fastlane Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# CocoaPods (opsiyonel - genellikle sistem CocoaPods kullanılır)
# gem "cocoapods", "~> 1.15"
